import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nasa Photo of the Day | Jorge Contreras</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>This works.</h1>
    </div>
  );
}
