import Head from "next/head";
import { Heading, Container, Text } from "@chakra-ui/react";
import Button from "../components/Button";
import Image from "../components/Image";

export default function Home() {
  const getDate = (separator = "/") => {
    let newDate = new Date();
    let date = newDate.getDate();
    let month = newDate.getMonth() + 1;
    let year = newDate.getFullYear();

    return `${
      month < 10 ? `0${month}` : `${month}`
    }${separator}${date}${separator}${year}`;
  };

  return (
    <div>
      <Head>
        <title>Nasa Photo of the Day | Jorge Contreras</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="1080px" textAlign="center">
        <Button />
        <Heading as="h1" size="4xl">
          NASA Photo of the Day
        </Heading>
        <Text>{getDate()}</Text>
        <Heading as="h2">Title</Heading>
        <Image />
        <Text>Description</Text>
      </Container>
    </div>
  );
}
